### PR TITLE
refactor: use type switch for checking color type

### PR DESCRIPTION
**Pull request by DaveSaah**
Addresses #35 

### Changes

- Break if statements for color type checking into switch cases.

    ```go
    switch v := b.TitleColor.(type) {
        case string:
        ...
        case uint:
        ...
        case [3]uint:
        ...
        default:
        ...
    }
    ```

- Replace hard coded boolean expression with a variable.

    ```go
    titleContainsNewLine := strings.Contains(title, "\n")
    ```

### CODE REVIEW

**Review by Delta456 — COMMENTED** [review]
Thanks for the PR! I appreciate it. It would help if you also changed the functions `obtainContentColor` and `obtainBoxColor`.

**Comment by DaveSaah** [comment]
Alright, noted ✅️

**Comment by DaveSaah** [comment]
- [x] refactor `obtainContentColor`
- [x] refactor `obtainBoxColor`

**Review by Delta456 — APPROVED** [review]
Good work!

**Pull request merged**
