### PR TITLE
Replaced errorMsg with err type

### PR DESCRIPTION
**Pull request by AniketNS**

### CODE REVIEW

**Review by Delta456 — CHANGES_REQUESTED** [review]
Also, change other occurrences where `roundOffColorVertical` and `roundOffTitleColor` is used

**Comment by AniketNS** [comment]
@Delta456, Can you please tell me current changes are correct or not?

**Comment by AniketNS** [comment]
Sorry, I accidentally closed the pull request.

**Comment by Delta456** [comment]
> @Delta456, Can you please tell me current changes are correct or not?

Current changes are correct but please go through what all changes are needed to do.

**Comment by AniketNS** [comment]
Sure @Delta456

**Comment by DaveSaah** [comment]
Hello 👋🏼 

Wanted to ask if there are other implementations that need to undergo this update?

**Comment by Delta456** [comment]
Closing due to inactivity.

**Pull request closed without merging**
